version: '3.7'

services:
  frontend:
    build:
      args: 
        - NODE_ENV=production
    restart: always
    environment:
      - VUE_APP_API_URL=${API_URL}

  nginx:
    build: server
    restart: always
    ports:
      - ${EXTERNAL_PORT}:80

  
