version: '3.7'

services:
  frontend:
    build:
      target: build
    command: yarn dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VUE_APP_API_URL=https://localhost:8000
    volumes:
      - ./frontend:/app
    ports:
      - 5000:3000