version: '3.7'

services:
  frontend:
    build:
      args: 
        - NODE_ENV=development
    command: yarn dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VUE_APP_API_URL=https://localhost:8000
    ports:
      - 5000:3000